version: 2

sources:
  - name: erp 
    schema: erp_northwind
    description: Fonte de dados de vendas do SAP Northwind
    tables:
      - name: employees
        columns:
          - name: employee_id
            tests:
              - unique
              - not_null
      - name: products
        columns:
          - name: product_id
            tests:
              - unique
              - not_null
      - name: categories
        columns:
          - name: category_id
            tests:
              - unique
              - not_null
      - name: suppliers
        columns:
          - name: supplier_id
            tests:
              - unique
              - not_null
      - name: customers
        columns:
          - name: customer_id
            tests:
              - unique
              - not_null
      - name: shippers
        columns:
          - name: shipper_id
            tests:
              - unique
              - not_null
      - name: orders
        columns:
          - name: order_id
            tests:
              - unique
              - not_null
      - name: order_details
